DATA:
  DATASET: 'nuscenes'
  # DATA_PATH: '../preproc_datasets/50m_1r_0l_0v_nostaticrad_onlyvehicles_onlymoving/all_scenes.npy'  #THIS TRAIN
  DATA_PATH: '../preproc_datasets/50m_1r_1l_0v_nostaticrad_onlyvehicles_onlymoving/all_scenes.npy'
  INPUT_SIZE: (6, 360)
  BATCH_SIZE: 128
  VAL_RATIO: 0.2
MODEL:
  TYPE: radarswin
  NAME: radarswin_tiny
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 1

  PRETRAINED: '../checkpoints/alpha_small/ckpt_epoch_125.pth'
  # RESUME: '../checkpoints/alpha_small/ckpt_epoch_125.pth'
  # RESUME: ''
  RADARSWIN:
    PATCH_SIZE: [1, 1]
    IN_CHANS: 3
    OUT_REG_HEADS: [1, 1, 2, 2, 2]
    EMBED_DIM: 24
    DEPTHS: [6, 12, 6, 6]
    NUM_HEADS: [2, 4, 4, 4]
    WINDOW_SIZES: [[6, 6], [6, 12], [3, 12], [1, 12]]
    MERGE_FACTORS: [[1, 1], [2, 1], [3, 1], [1, 1]]
    REDUCTION_FACTORS: [1, 2, 2, 1]
    MLP_RATIO: 4.0
    QKV_BIAS: True
    QK_SCALE: None
    TEMPORAL_ATTENTION: True
    # ATTENTION_DROP_RATE: 0.0
    
    RANGE_LOSS_WEIGHT: 0.1
    BBOX_LOSS_WEIGHT: 1.0
    VELOCITY_LOSS_WEIGHT: 0.1
  
TRAIN:
  EPOCHS: 1000
  WARMUP_EPOCHS: 4
  WEIGHT_DECAY: 0.01
  # BASE_LR: 1.25e-4 # 4096 batch-size
  # WARMUP_LR: 1.25e-7
  # MIN_LR: 1.25e-6
  CLIP_GRAD: 5.0
  ACCUMULATION_STEPS: 1

  BASE_LR: 1.25e-5 # my choice
  # BASE_LR: 5.0e-4 # my choice
  WARMUP_LR: 1.25e-6
  # WARMUP_LR: 1.25e-5
  MIN_LR: 1.25e-6
  AUTO_RESUME: False

FUSED_LAYERNORM: False
FUSED_WINDOW_PROCESS: False
SAVE_FREQ: 5

EVAL_MODE: True
