DATA:
  DATASET: 'nuscenes'
  DATA_PATH: '../preproc_datasets/abs_50m_1r_0l_0v_more/all_targets/all_scenes.npy'
  INPUT_SIZE: (6, 360)
  BATCH_SIZE: 128
  VAL_RATIO: 0.2

TAG: all_targets_more_track
MODEL:
  TYPE: radarswin
  NAME: beta_small
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 1

  TRACKING: True

  # RESUME: '../model_code/beta_small/all_targets_more_track/ckpt_epoch_465.pth'

  PRETRAINED: '../model_code/beta_small/all_targets_more_track/ckpt_epoch_505.pth'

  RADARSWIN:
    PATCH_SIZE: [1, 1]
    IN_CHANS: 3
    OUT_REG_HEADS: [1, 1, 2, 2, 2]
    EMBED_DIM: 24
    DEPTHS: [2, 6, 2, 4]
    NUM_HEADS: [1, 1, 1, 1]
    WINDOW_SIZES: [[6, 6], [6, 6], [3, 6], [1, 20]]
    MERGE_FACTORS: [[1, 1], [2, 1], [3, 1], [1, 1]]
    REDUCTION_FACTORS: [1, 2, 2, 1]
    MLP_RATIO: 4.0
    QKV_BIAS: True
    QK_SCALE: None
    TEMPORAL_ATTENTION: True
    # ATTENTION_DROP_RATE: 0.0
    
    RANGE_LOSS_WEIGHT: 0.1
    BBOX_LOSS_WEIGHT: 1.0
    VELOCITY_LOSS_WEIGHT: 0.1

CENTERNET:
  PRED_HEATMAP_THR: 0.25

METRICS:
  AP_THR: [0.5, 1.0, 2.0, 4.0]

TRAIN:
  EPOCHS: 800
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.01
  # BASE_LR: 1.25e-4 # 4096 batch-size
  # WARMUP_LR: 1.25e-7
  # MIN_LR: 1.25e-6
  CLIP_GRAD: 5.0
  ACCUMULATION_STEPS: 1

  BASE_LR: 1.25e-5 # my choice
  WARMUP_LR: 1.25e-6
  # BASE_LR: 5.0e-4 
  # WARMUP_LR: 1.25e-5

  MIN_LR: 1.25e-7
  AUTO_RESUME: False

FUSED_LAYERNORM: False
FUSED_WINDOW_PROCESS: False
SAVE_FREQ: 5

EVAL_MODE: True
ALL_SCENE_PARALLEL: True
